### ISSUE TITLE
start dev without yarn

### ISSUE THREAD

**Issue by TomishaCom** [jefrydco/nuxt-pwa-vuetify-firebase-ssr#3]
is posible start the dev with npm?

**Comment by jefrydco** [comment]
Sure, you can use any package manager you like to run this starter project. But first, take a look on `package.json` file, if there is specific command with `yarn` prefix, you could change that into your own package manager. For instance, in this section https://github.com/jefrydco/nuxt-pwa-vuetify-firebase-ssr/blob/be67f8f09a20cc19eeec15bb6a2ef9b673e3cd7e/package.json#L36

You could change that to use npm instead of yarn, and it becomes

```
"test": "npm test:unit",
```

**Comment by TomishaCom** [comment]
unfortunately this is not possible

![image](https://user-images.githubusercontent.com/47674859/54738242-af130800-4bb3-11e9-9376-313832046199.png)

**Comment by jefrydco** [comment]
@TomishaCom Ah, that thing is caused by sentry module for nuxt, it should has Sentry DSN added into `.env`.
https://github.com/jefrydco/nuxt-pwa-vuetify-firebase-ssr/blob/be67f8f09a20cc19eeec15bb6a2ef9b673e3cd7e/.env.example#L2

If you dont want to use Sentry, you can just disable it here
https://github.com/jefrydco/nuxt-pwa-vuetify-firebase-ssr/blob/be67f8f09a20cc19eeec15bb6a2ef9b673e3cd7e/nuxt.config.js#L44

After that, it will be running well again
![image](https://user-images.githubusercontent.com/20434351/54757103-1fee0a80-4c1c-11e9-9f0e-84a3c5fbf9fb.png)
